services:
  springboot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://anguido:tonyjr07@cluster0.mz475.mongodb.net/myDatabase?retryWrites=true&w=majority&appName=Cluster0&ssl=true
